package MyBatis3.dao;

import MyBatis3.po.EmployeePO;
import MyBatis3.po.EmployeePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:51:26 CST 2022
     */
    long countByExample(EmployeePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:51:26 CST 2022
     */
    int deleteByExample(EmployeePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:51:26 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:51:26 CST 2022
     */
    int insert(EmployeePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:51:26 CST 2022
     */
    int insertSelective(EmployeePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:51:26 CST 2022
     */
    List<EmployeePO> selectByExample(EmployeePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:51:26 CST 2022
     */
    EmployeePO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:51:26 CST 2022
     */
    int updateByExampleSelective(@Param("record") EmployeePO record, @Param("example") EmployeePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:51:26 CST 2022
     */
    int updateByExample(@Param("record") EmployeePO record, @Param("example") EmployeePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:51:26 CST 2022
     */
    int updateByPrimaryKeySelective(EmployeePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:51:26 CST 2022
     */
    int updateByPrimaryKey(EmployeePO record);
}