package MyBatis3Simple.dao;

import MyBatis3Simple.po.EmployeePO;
import java.util.List;

public interface EmployeePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:50:56 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:50:56 CST 2022
     */
    int insert(EmployeePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:50:56 CST 2022
     */
    EmployeePO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:50:56 CST 2022
     */
    List<EmployeePO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Wed Jan 19 18:50:56 CST 2022
     */
    int updateByPrimaryKey(EmployeePO record);
}